import {Router} from 'express';
import Food from '../models/Food.js';
import Order from '../models/Order.js';
import Reservation from '../models/Reservation.js';
import Event from '../models/Event.js';
import Customer from '../models/Customer.js';
import {adminGuard} from '../middleware/admin.js';
const router=Router();
router.get('/menu',async(req,res,next)=>{try{const q={isAvailable:true};if(req.query.category&&req.query.category!=='All')q.category=req.query.category;const foods=await Food.find(q).sort({category:1,name:1});res.json(foods);}catch(e){next(e)}});
router.get('/menu/:id',async(req,res,next)=>{try{const f=await Food.findById(req.params.id);if(!f)return res.status(404).json({message:'Food not found'});res.json(f)}catch(e){next(e)}});
router.post('/orders',async(req,res,next)=>{try{const {customer,items,paymentMethod='cod',notes}=req.body;if(!customer?.name||!customer?.phone||!Array.isArray(items)||!items.length)return res.status(400).json({message:'Name, phone and at least one item are required'});const subtotal=items.reduce((s,i)=>s+(Number(i.price)||0)*(Number(i.qty)||0),0);const deliveryFee=subtotal?60:0;const serviceFee=Math.round(subtotal*.05);const order=new Order({orderNumber:'VL-'+Date.now().toString().slice(-7),customer,items,subtotal,deliveryFee,serviceFee,total:subtotal+deliveryFee+serviceFee,paymentMethod,notes});await order.save();let c=await Customer.findOne(customer.email?{email:customer.email}:{phone:customer.phone});if(!c)c=new Customer({name:customer.name,email:customer.email,phone:customer.phone,address:customer.address});c.name=customer.name;c.orderCount+=1;c.totalSpent+=order.total;c.address=customer.address||c.address;await c.save();res.status(201).json({message:'Order placed successfully',order})}catch(e){next(e)}});
router.post('/reservations',async(req,res,next)=>{try{const {name,phone,email,date,time,guests,occasion,notes}=req.body;if(!name||!phone||!date||!time||!guests)return res.status(400).json({message:'Name, phone, date, time and guests are required'});const reservation=await Reservation.create({name,phone,email,date,time,guests:Number(guests),occasion,notes});res.status(201).json({message:'Reservation request received',reservation})}catch(e){next(e)}});
router.post('/events',async(req,res,next)=>{try{const {eventType,date,guests,budget,name,phone,email,details}=req.body;if(!date||!name||!phone)return res.status(400).json({message:'Date, name and phone are required'});const event=await Event.create({eventType,date,guests,budget,name,phone,email,details});res.status(201).json({message:'Event request received',event})}catch(e){next(e)}});
router.get('/orders',adminGuard,async(req,res,next)=>{try{res.json(await Order.find().sort({createdAt:-1}).limit(200))}catch(e){next(e)}});
router.patch('/orders/:id',adminGuard,async(req,res,next)=>{try{const order=await Order.findByIdAndUpdate(req.params.id,{status:req.body.status,paymentStatus:req.body.paymentStatus},{new:true});if(!order)return res.status(404).json({message:'Order not found'});res.json(order)}catch(e){next(e)}});
router.get('/reservations',adminGuard,async(req,res,next)=>{try{res.json(await Reservation.find().sort({date:1,time:1}).limit(200))}catch(e){next(e)}});
router.patch('/reservations/:id',adminGuard,async(req,res,next)=>{try{const r=await Reservation.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true});res.json(r)}catch(e){next(e)}});
router.get('/events',adminGuard,async(req,res,next)=>{try{res.json(await Event.find().sort({date:1}).limit(200))}catch(e){next(e)}});
router.get('/customers',adminGuard,async(req,res,next)=>{try{res.json(await Customer.find().sort({totalSpent:-1}).limit(200))}catch(e){next(e)}});
router.get('/stats',adminGuard,async(req,res,next)=>{try{const [orders,reservations,customers]=await Promise.all([Order.countDocuments(),Reservation.countDocuments(),Customer.countDocuments()]);const revenue=(await Order.aggregate([{$match:{status:{$ne:'cancelled'}}},{$group:{_id:null,total:{$sum:'$total'}}}]))[0]?.total||0;res.json({orders,reservations,customers,revenue})}catch(e){next(e)}});
router.post('/menu',adminGuard,async(req,res,next)=>{try{res.status(201).json(await Food.create(req.body))}catch(e){next(e)}});
router.patch('/menu/:id',adminGuard,async(req,res,next)=>{try{res.json(await Food.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true}))}catch(e){next(e)}});
router.delete('/menu/:id',adminGuard,async(req,res,next)=>{try{await Food.findByIdAndDelete(req.params.id);res.status(204).end()}catch(e){next(e)}});
export default router;
